<div class="page-header">
    <h2>Cumplimiento de fechas</h2>
</div>

<div class="row">

    <div class="col-md-12">
        <div class="panel panel-green">
            <div class="panel-heading">Acreedores</div>
            <div class="panel-body row">

                <div class="chart col-xs-12 col-sm-7 col-md-7 col-lg-8">
                    <div id="cumplimiento-acreedor"></div>
                </div>

                <div class="detail col-xs-12 col-sm-5 col-md-5 col-lg-4">
                    <table class="table table-condensed">
                        <thead>
                            <tr>
                                <th>Informes</th>
                                <th class="text-center"><span class="color-blue">◼</span> Cumplidos</th>
                                <th class="text-center"><span class="color-grey">◼</span> Incumplidos</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Emisión de los DTE</td>
                                <td class="text-center">69.23%</td>
                                <td class="text-center">30.76%</td>
                            </tr>
                            <tr>
                                <td>Recepción de los DTE</td>
                                <td class="text-center">11.11%</td>
                                <td class="text-center">88.88%</td>
                            </tr>
                            <tr>
                                <td>Aceptación del Servicio</td>
                                <td class="text-center">62.5%</td>
                                <td class="text-center">37.5%</td>
                            </tr>
                            <tr>
                                <td>Pagos</td>
                                <td class="text-center">25%</td>
                                <td class="text-center">75%</td>
                            </tr>
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>

    <div class="col-md-12">
        <div class="panel panel-green">
            <div class="panel-heading">Deudores</div>
            <div class="panel-body row">

                <div class="chart col-xs-12 col-sm-7 col-md-7 col-lg-8">
                    <div id="cumplimiento-deudor"></div>
                </div>

                <div class="detail col-xs-12 col-sm-5 col-md-5 col-lg-4">
                    <table class="table table-condensed">
                        <thead>
                            <tr>
                                <th>Informes</th>
                                <th class="text-center"><span class="color-blue">◼</span> Cumplidos</th>
                                <th class="text-center"><span class="color-grey">◼</span> Incumplidos</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Aceptación del Servicio</td>
                                <td class="text-center">62.5%</td>
                                <td class="text-center">37.5%</td>
                            </tr>
                            <tr>
                                <td>Pagos</td>
                                <td class="text-center">25%</td>
                                <td class="text-center">75%</td>
                            </tr>
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>

</div>
