var years = [
    2014,
    2015,
    2016,
    2017,
];


var months = [
    'Ene',
    'Feb',
    'Mar',
    'Abr',
    'May',
    'Jun',
    'Jul',
    'Ago',
    'Sep',
    'Oct',
    'Nov',
    'Dic',
];


var participants = [
    'AJTE',
    'Abengoa',
    'Aela',
    'Alba',
    'Amanecer Solar',
    'Andes Generación',
    'Arauco Bioenergía',
    'Barrick Generación',
    'Bellavista',
    'Beneo Orafti',
    'Bio Energía Molina',
    'Biocruz Generación',
    'CELMSA',
    'CGE Distribución',
    'Carbomet',
    'Carrán',
    'Central Hidroeléctrica Rio Mulchén',
    'Chanleufu',
    'Chilectra',
    'Chilquinta',
    'Chungungo',
    'Colbún',
    'Collil',
    'Comasa',
    'Commonplace',
    'Contra',
    'Curileufu',
    'CuzCuz',
    'Dener',
    'Divisadero',
    'Donguil Energía',
    'Dosal',
    'Duke Energy',
    'EBCO Atacama',
    'EDAM LTDA.',
    'EGP del Sur SpA',
    'EMELDA',
    'ERNC I',
    'El Agrio',
    'El Arrayán',
    'El Arroyo',
    'El Boco',
    'El Raso',
    'Elektragen',
    'Eletrans',
    'Eléctrica Caren',
    'Eléctrica El Galpón',
    'Eléctrica Licán',
    'Endesa',
    'Enerbosch',
    'Energía León',
    'Energía Pacífico',
    'Energías del Futuro',
    'Enlasa',
    'Equipos Generación',
    'Eólica La Esperanza',
    'Frontel',
    'GENPAC',
    'GESTEL',
    'GR ARAUCARIA',
    'GR COIGÜE',
    'GR HUINGAN',
    'GR Pan de Azúcar',
    'Generadora Piutel',
    'Generadora Roblería',
    'Gesan',
    'Guacolda',
    'HBS Energía',
    'HBS GNL',
    'HIDROBONITO',
    'HORMIGA SOLAR',
    'HidroMaule',
    'HidroMuchi',
    'Hidroangol',
    'Hidrocallao',
    'Hidroelec',
    'Hidroeléctrica Allipén',
    'Hidroeléctrica Cumpeo',
    'Hidroeléctrica Diuto',
    'Hidroeléctrica Dongo',
    'Hidroeléctrica El Manzano',
    'Hidroeléctrica El Mirador',
    'Hidroeléctrica La Arena',
    'Hidroeléctrica La Confluencia',
    'Hidroeléctrica La Higuera',
    'Hidroeléctrica Puclaro',
    'Hidroeléctrica Rio Huasco',
    'Hidroeléctrica San Andrés',
    'Hidronalcas',
    'Hidropaloma',
    'Huajache',
    'Imelsa',
    'La Montaña 1',
    'Las Flores',
    'Las Pampas',
    'Lleuquereo',
    'Los Espinos',
    'Los Padres Hidro',
    'Los Pinos Bio',
    'Luna',
    'Luz del Norte',
    'Mainco',
    'Molinera Villarrica',
    'Norvind',
    'Nueva Degan',
    'PMGD Bureo',
    'PSF Lomas Coloradas',
    'PSF Pama',
    'Pacific Hydro',
    'Pacific Hydro Chacayes',
    'Parque Eólico Lebu',
    'Parque Eólico Los Cururos',
    'Parque Solar Los Loros',
    'Pehuenche',
    'Pichilonco',
    'Puntilla',
    'Raki',
    'Renovalia Chile Seis, SPA',
    'Renovalia Chile Siete, SPA',
    'Rio Alto SA',
    'Rio Puma',
    'Rucatayo',
    'SGA',
    'STS',
    'SWC',
    'San Andrés',
    'San Juan',
    'Santa Irene',
    'Santa Marta',
    'Sol',
    'Stericycle',
    'Subsole',
    'Sunenergreen (Altos del Paico)',
    'Tamm',
    'Teatinos',
    'Tiltil Solar',
    'Tomaval Generación',
    'Trailelfu',
    'TransChile',
    'Transelec',
    'Ucuquer',
    'Ucuquer Dos',
];
